logging:
  level:
    tech:
      jhipster:
        reactapp: INFO
spring:
  application:
    name: Reactapp
  threads:
    virtual:
      enabled: true
  security:
    user:
      name: admin
      password: $2a$12$cRKS9ZURbdJIaRsKDTDUmOrH4.B.2rokv8rrkrQXr2IR2Hkna484O
      roles: ADMIN
server:
  port: 8081
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
        - configprops
        - env
        - health
        - info
        - logfile
        - loggers
        - threaddump
application:
  security:
    jwt-base64-secret: NmE2NDhmMmQ5OWQzYzk4NmE4NjNlMmQzNmU3ZTU4ZDY2MmUxOWEwZGI4YTk4NDY0MTk4MmQyMWZlNDNlM2FjYg==
    content-security-policy: 'default-src ''self''; frame-src ''self'' data:; script-src
      ''self'' ''unsafe-inline'' ''unsafe-eval'' https://storage.googleapis.com; style-src
      ''self'' ''unsafe-inline'' https://fonts.googleapis.com; img-src ''self'' data:;
      font-src ''self'' data: https://fonts.gstatic.com;'
    remember-me-token-validity: P365D
    token-validity: P1D
